services:
  stats-db:
    image: postgres:16.1
    container_name: stats-db
    ports:
      - "5433:5432"
    volumes:
      - ./volumes/stats-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: stats
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: 12345
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U dbuser -d stats" ]
      interval: 5s
      timeout: 5s
      retries: 5

  ewm-db:
    image: postgres:16.1
    container_name: ewm-db
    ports:
      - "5434:5432"
    volumes:
      - ./volumes/ewm-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ewm
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: 12345
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U dbuser -d ewm" ]
      interval: 5s
      timeout: 5s
      retries: 5

  stats-server:
    image: stats-server
    build:
      context: ./stats-service/stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/stats
      SPRING_DATASOURCE_USERNAME: dbuser
      SPRING_DATASOURCE_PASSWORD: 12345
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
      SPRING_LIQUIBASE_ENABLED: false
      SPRING_PROFILES_ACTIVE: docker
    restart: unless-stopped
    depends_on:
      stats-db:
        condition: service_healthy

  ewm-service:
    image: main-service
    build:
      context: ./main-service
    container_name: ewm-service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ewm-db:5432/ewm
      SPRING_DATASOURCE_USERNAME: dbuser
      SPRING_DATASOURCE_PASSWORD: 12345
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
      SPRING_LIQUIBASE_ENABLED: false
      SPRING_PROFILES_ACTIVE: docker
      STATS_SERVER_URL: http://stats-server:9090
    restart: unless-stopped
    depends_on:
      ewm-db:
        condition: service_healthy
